modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_dynamics"
version = "${file.jarVersion}"
displayName = "Thermal Dynamics"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_dynamics.png"
credits = "Team CoFH"
authors = "King Lemming, covers1624"
description = '''
Thermal gets dynamic!

Contains various logistic options for technical gameplay!
'''
[[dependencies.thermal_dynamics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "forge"
mandatory = true
versionRange = "[40.1.76,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "cofh_core"
mandatory = true
versionRange = "[9.2,9.3]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_dynamics]]
modId = "thermal"
mandatory = true
versionRange = "[9.2,9.3]"
ordering = "AFTER"
side = "BOTH"